sitegroup: '2018-texascamp'

shared:
  production:
    - src: files
      dst: web/sites/default/files
services:
  node:
    amazeeio:
      type: node:8
      template: frontend/.amazeeio.node.yml
    build:
      context: frontend
      dockerfile: Dockerfile
